### ISSUE TITLE
Missing stuffs not documented: pipeline, git-ssh-credentials

### ISSUE THREAD

**Issue by cmoulliard** [parodos-dev/workflow-software-templates#22]
## Issue 

Some of the resources created using the skeleton project such as the Tekton [Trigger](https://github.com/parodos-dev/workflow-software-templates/blob/main/scaffolder-templates/basic-workflow/tekton/trigger.yaml) refers to resources which are missing: 
- pipeline => workflow-deployment
- secret => git-ssh-credentials

Can the template be improved to generate them OR to document what the user should do to install them ?

**Comment by pkliczewski** [comment]
@dmartinol please take a look

**Comment by dmartinol** [comment]
I already discussed this issue with @masayag, we need to document the steps to generate the missing resources, that are currently described [here](https://github.com/parodos-dev/workflows-tekton-pipeline?tab=readme-ov-file#installing-docker-credentials) and [here](https://github.com/parodos-dev/workflows-tekton-pipeline?tab=readme-ov-file#install).

The latter will be eventually moved in the Orchestrator helm chart, according to [FLPATH-1063](https://issues.redhat.com/browse/FLPATH-1063), so there will be no need of any manual deployment.

**Comment by pkliczewski** [comment]
@dmartinol thanks! @cmoulliard this work is tracked by [FLPATH-1063](https://issues.redhat.com/browse/FLPATH-1063) is it ok with you to close this issue?

**Comment by pkliczewski** [comment]
With this solution we target OCP but we use k8s. @rgolangh is working on extending our helm chart to support k8s deployment as well

**Comment by rgolangh** [comment]
in the works https://github.com/parodos-dev/orchestrator-helm-chart/pull/90
- you can try it
